### PR TITLE
ui fixes

### LINKED ISSUE #739: missing preloader when README is loading in the package details page

### PR DESCRIPTION
**Pull request by getneil**
resolves #739 

show ukrainian translation

### CODE REVIEW

File: svelte/src/components/preloader/preloader.svelte [hunk 1]
```diff
@@ -4,6 +4,12 @@
...
 </script>
 
-<figure class="flex h-full w-full items-center justify-center bg-black bg-opacity-90 py-8">
+<figure class="container flex h-full w-full flex-row justify-center bg-black bg-opacity-90 py-8">
   <i class="icon-tea-logo-iconasset-1 text-gray animate-pulse text-4xl" />
 </figure>
+
+<style>
+  .container {
+    display: flex;
```
Comment (getneil) [inline svelte/src/components/preloader/preloader.svelte:13]: not sure why flex class is not working.

**Review by ABevier — APPROVED** [review]
LGTM
