### PR TITLE
change image loading

### LINKED ISSUE #706: Wrong image usage
image
There appears to be an issue with re-using images while rendering package grids
Likely related to latency or missing images, but image "carry-overs" during rendering iterations should be prevented
If this is deep into the svelte rendering, consider adding post-render validation

### PR DESCRIPTION
**Pull request by ABevier**
Load images more in line with how the svelte docs say we should do this.  It greatly simplifies the overall code and removes the race that causes the wrong image to display for a package.

Closes #706

### CODE REVIEW

File: svelte/src/components/package-card/bg-image.svelte [hunk 1]
```diff
@@ -1,92 +1,35 @@
 <script lang="ts">
-  import type { GUIPackage } from "$libs/types";
-  import { packagesStore } from "$libs/stores";
+  import { defaultImgUrl, type GUIPackage } from "$libs/types";
```
Comment (getneil) [inline svelte/src/components/package-card/bg-image.svelte:2]: this seems unused anymore

**Review by getneil — APPROVED** [review]
LGTM!
